# Config file for automatic testing at travis-ci.org
sudo: false

language: python

python:
  - "2.7"
  - "3.4"

install:
  - pip install tox coverage
  - coverage erase

# command to run tests, e.g. python setup.py test
script:
  - tox -e py

after_success:
    - coverage combine
    # Report coverage results to codecov.io
    - pip install codecov
    - codecov
